from tkinter import *
from tkinter import ttk
import pandas as pd
from openpyxl import load_workbook

class NewForm:
    def main(self):
        self.window = Toplevel()
        self.window.title('New Form')
        self.file_path = 'StudentDetails.xlsx'
        self.sheet_name = 'Sheet1'
        self.name_var = StringVar()
        self.date_var = StringVar()
        self.month_var = StringVar()
        self.year_var = StringVar()
        self.dept_var = StringVar()
        self.email_var = StringVar()
        self.phone_var = StringVar()
        self.address_var = StringVar()
        self.guardian_var = StringVar()
        self.class_12_var = StringVar()
        self.class_10_var = StringVar()

        self.create()

    def create(self):
        intro_frame = Frame(self.window, pady=30)
        intro_frame.grid(row=0)
        heading = Label(intro_frame, text='NEW FORM', width=100)
        heading.grid(row=0, column=1)
        name_frame = Frame(self.window, pady=30)
        name_frame.grid(row=1)
        name_label = Label(name_frame, text='Name:', width=20)
        name_label.grid(row=1, column=0)
        name = Entry(name_frame, textvariable=self.name_var, width=100, bd=5)
        name.grid(row=1, column=1)
        dob_frame = Frame(self.window, pady=20)
        dob_frame.grid(row=2)
        dob_label = Label(dob_frame, text='Date of Birth:', width=20)
        dob_label.grid(row=2, column=0)
        date = ttk.Combobox(dob_frame, textvariable=self.date_var, values=[i for i in range(1,32)])
        date.grid(row=2, column=1)
        month = ttk.Combobox(dob_frame, textvariable=self.month_var, values=[i for i in range(1,13)])
        month.grid(row=2, column=2)
        year = ttk.Combobox(dob_frame, textvariable=self.year_var, values=[i for i in range(2000, 2024)])
        year.grid(row=2, column=3)
        dept_frame = Frame(self.window, pady=20)
        dept_frame.grid(row=3)
        dept_label = Label(dept_frame, text='Department:', width=20)
        dept_label.grid(row=3, column=0)
        Radiobutton(dept_frame, text='CSE-A', variable=self.dept_var, value='CSE-A').grid(row=3, column=1)
        Radiobutton(dept_frame, text='CSE-B', variable=self.dept_var, value='CSE-B').grid(row=3, column=2)
        Radiobutton(dept_frame, text='IT', variable=self.dept_var, value='IT').grid(row=3, column=3)
        Radiobutton(dept_frame, text='AIML', variable=self.dept_var, value='AIML').grid(row=3, column=4)
        Radiobutton(dept_frame, text='ECE', variable=self.dept_var, value='ECE').grid(row=3, column=5)
        Radiobutton(dept_frame, text='EE', variable=self.dept_var, value='EE').grid(row=3, column=6)
        email_frame = Frame(self.window, pady=20)
        email_frame.grid(row=4)
        email_label = Label(email_frame, text='Email:', width=20)
        email_label.grid(row=4, column=0)
        email = Entry(email_frame, textvariable=self.email_var, width=100, bd=5)
        email.grid(row=4, column=1)
        phone_frame = Frame(self.window, pady=20)
        phone_frame.grid(row=5)
        phone_label = Label(phone_frame, text='Phone: \t +91', width=10)
        phone_label.grid(row=5, column=0)
        phone = Entry(phone_frame, textvariable=self.phone_var, width=100, bd=5)
        phone.grid(row=5, column=1)
        address_frame = Frame(self.window, pady=20)
        address_frame.grid(row=6)
        address_label = Label(address_frame, text='Address:', width=20)
        address_label.grid(row=6, column=0)
        address = Entry(address_frame, textvariable=self.address_var, width=100, bd=5)
        address.grid(row=6, column=1)
        guardian_frame = Frame(self.window, pady=20)
        guardian_frame.grid(row=7)
        guardian_label = Label(guardian_frame, text='Guardian:', width=20)
        guardian_label.grid(row=7, column=0)
        guardian = Entry(guardian_frame, textvariable=self.guardian_var, width=100, bd=5)
        guardian.grid(row=7, column=1)
        class_12_frame = Frame(self.window, pady=20)
        class_12_frame.grid(row=8)
        class_12_label = Label(class_12_frame, text='Class 12 %:', width=20)
        class_12_label.grid(row=8, column=0)
        class_12 = Entry(class_12_frame, textvariable=self.class_12_var, width=10, bd=5)
        class_12.grid(row=8, column=1)
        class_12_label = Label(class_12_frame, text='%', width=5)
        class_12_label.grid(row=8, column=2)
        class_10_frame = Frame(self.window, pady=20)
        class_10_frame.grid(row=9)
        class_10_label = Label(class_10_frame, text='Class 10 %:', width=20)
        class_10_label.grid(row=9, column=0)
        class_10 = Entry(class_10_frame, textvariable=self.class_10_var, width=10, bd=5)
        class_10.grid(row=9, column=1)
        class_10_label = Label(class_10_frame, text='%', width=5)
        class_10_label.grid(row=9, column=2)
        button_frame = Frame(self.window, pady=20)
        button_frame.grid(row=10)
        submit = Button(button_frame, text='Submit', bg='green', fg='white', width=10, command=self.submit_form)
        submit.grid(row=10, column=0, padx=10)
        clear = Button(button_frame, text='Clear', bg='light blue', fg='black', width=10, command=self.clear_form)
        clear.grid(row=10, column=1, padx=10)
        back = Button(button_frame, text='Back', bg='white', fg='black', width=10, command=self.window.destroy)
        back.grid(row=10, column=2, padx=10)

    def submit_form(self):
        try:
            existing_data = pd.read_excel("StudentDetails.xlsx", engine='openpyxl')
        except FileNotFoundError:
            existing_data = pd.DataFrame(columns=["REG. NO.", "NAME", "DOB", "DEPT", "EMAIL", "PHONE", "ADDRESS", "GUARDIAN", "CLASS 12", "CLASS 10"])

        max_roll_number = existing_data["REG. NO."].max() if not existing_data.empty else 0
        next_roll_number = max_roll_number + 1
        dob = f"{self.date_var.get()}/{self.month_var.get()}/{self.year_var.get()}"
        data = [next_roll_number, self.name_var.get(), dob, self.dept_var.get(), self.email_var.get(), self.phone_var.get(), self.address_var.get(), self.guardian_var.get(), self.class_12_var.get(), self.class_10_var.get()]
        new_entry = pd.DataFrame([data], columns=["REG. NO.", "NAME", "DOB", "DEPT", "EMAIL", "PHONE", "ADDRESS", "GUARDIAN", "CLASS 12", "CLASS 10"])
        updated_data = pd.concat([existing_data, new_entry], ignore_index=True)
        updated_data.to_excel("StudentDetails.xlsx", index=False, engine='openpyxl')
        print("Data successfully added with Roll Number:", next_roll_number)
        self.clear_form()

    def clear_form(self):
        self.name_var.set("")
        self.date_var.set("")
        self.month_var.set("")
        self.year_var.set("")
        self.dept_var.set("")
        self.email_var.set("")
        self.phone_var.set("")
        self.address_var.set("")
        self.guardian_var.set("")
        self.class_12_var.set("")
        self.class_10_var.set("")
